"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, BadgeIndianRupee, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Eye, EyeOff, FileCheck2, FileText, LayoutDashboard, Menu, PackageCheck, PanelLeftClose, PanelLeftOpen, ReceiptIndianRupee, RefreshCcw, Search, Sparkles, Truck, Users, X, AlertTriangle } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { TenderDiscovery } from "@/components/tender-discovery";
import { customers, dashboardTotals, dispatches, invoices, outstandingFor, plates, priceLists, stockMovements, suppliers, tenders, DEMO_CLOCK, type Tender } from "@/lib/demo-data";

type PageKey = "dashboard" | "stock" | "customers" | "pricing" | "dispatch" | "quotations" | "accounts" | "payments" | "tenders";
type Detail = { type: "stock" | "customers" | "suppliers" | "tenders" | "attention" | "guide"; id?: string } | null;
const money=(p:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(p/100);
const compactMoney=(p:number)=>{const r=p/100;return r>=10000000?`₹${(r/10000000).toFixed(2)} Cr`:r>=100000?`₹${(r/100000).toFixed(2)} L`:money(p)};
const tonnes=(kg:number)=>`${(kg/1000).toFixed(1)} t`;
const formatDate=(s:string,o?:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat("en-IN",o??{day:"numeric",month:"short",year:"numeric"}).format(new Date(s));
const ago=(s:string)=>{const h=Math.floor((new Date(DEMO_CLOCK).getTime()-new Date(s).getTime())/3600000);return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`};

const navGroups=[
  {label:"Overview",items:[{key:"dashboard" as PageKey,label:"Dashboard",icon:LayoutDashboard}]},
  {label:"Operations",items:[{key:"stock" as PageKey,label:"Plates Stock",icon:Archive},{key:"customers" as PageKey,label:"Customers",icon:Users},{key:"pricing" as PageKey,label:"Pricing",icon:BadgeIndianRupee},{key:"dispatch" as PageKey,label:"Dispatch & Documents",icon:Truck},{key:"quotations" as PageKey,label:"Quotations",icon:FileText}]},
  {label:"Finance",items:[{key:"accounts" as PageKey,label:"Accounts",icon:BookOpen},{key:"payments" as PageKey,label:"Payments",icon:CircleDollarSign}]},
  {label:"Opportunities",items:[{key:"tenders" as PageKey,label:"Tenders",icon:BriefcaseBusiness}]}
];
const scaffolds:Record<Exclude<PageKey,"dashboard">,{title:string;subtitle:string;copy:string;bullets:string[];icon:typeof Archive}>={
  stock:{title:"Plates Stock",subtitle:"Receive, find, cut and issue every plate.",copy:"Track heat numbers, test certificates, godown locations and complete movement history.",bullets:["Goods receipt and plate tagging","Cut and issue traceability","Minimum stock alerts"],icon:Archive},
  customers:{title:"Customers",subtitle:"Commercial context in one place.",copy:"Review contacts, purchases, quotations, balances and customer-specific markups.",bullets:["Contact and delivery details","Purchase and quote history","Approved pricing rules"],icon:Users},
  pricing:{title:"Pricing",subtitle:"Turn source rates into approved customer prices.",copy:"Review sample Jindal Excel prices, apply customer markups and approve price-list previews.",bullets:["Source file review","Customer markup controls","Approval history"],icon:BadgeIndianRupee},
  dispatch:{title:"Dispatch & Documents",subtitle:"Move material with the right paperwork.",copy:"Select plates, record transport details and preview dispatch sheets and TC verification records.",bullets:["Plate and heat selection","Transport details","Dispatch-to-invoice matching"],icon:Truck},
  quotations:{title:"Quotations",subtitle:"Prepare consistent offers and follow outcomes.",copy:"Create branded quotations and track Draft, Sent, Accepted and Lost stages.",bullets:["Branded quote preview","Revision history","Sales status tracking"],icon:FileText},
  accounts:{title:"Accounts",subtitle:"A future read-only Tally overview.",copy:"Review accounting information and reconcile dispatches to official GST invoices held in Tally.",bullets:["Read-only ledger view","Dispatch reconciliation","Outstanding summaries"],icon:BookOpen},
  payments:{title:"Payments",subtitle:"Know what to collect and what to pay.",copy:"Organise customer collections, supplier dues, due dates and follow-up notes.",bullets:["To Collect","To Pay","Follow-up notes"],icon:CircleDollarSign},
  tenders:{title:"Tenders",subtitle:"Move opportunities from discovery to outcome.",copy:"Review New, Reviewing, Preparing, Submitted, Won, Lost and Skipped records with document checklists.",bullets:["Relevance review","Deadline and EMD tracking","Document checklist"],icon:BriefcaseBusiness}
};

export default function Home(){
  const [entered,setEntered]=useState(false),[showPassword,setShowPassword]=useState(false),[collapsed,setCollapsed]=useState(false),[mobileNav,setMobileNav]=useState(false),[resetOpen,setResetOpen]=useState(false);
  const [page,setPage]=useState<PageKey>("dashboard"),[detail,setDetail]=useState<Detail>(null),[range,setRange]=useState<7|30>(7),[query,setQuery]=useState(""),[tourStep,setTourStep]=useState(0);
  useEffect(()=>{if(localStorage.getItem("focal-diksha-demo-v1")){const id=window.setTimeout(()=>setEntered(true),0);return()=>window.clearTimeout(id)}},[]);
  const enter=()=>{localStorage.setItem("focal-diksha-demo-v1",JSON.stringify({entered:true}));setEntered(true)};
  const go=(p:PageKey)=>{setPage(p);setMobileNav(false);setQuery("");scrollTo({top:0,behavior:"smooth"})};
  const logout=()=>{localStorage.removeItem("focal-diksha-demo-v1");setEntered(false);setPage("dashboard")};
  const reset=()=>{localStorage.setItem("focal-diksha-demo-v1",JSON.stringify({entered:true}));setPage("dashboard");setRange(7);setQuery("");setDetail(null);setResetOpen(false)};
  const results=useMemo(()=>{if(query.trim().length<2)return[];const q=query.toLowerCase();return [
    ...plates.filter(p=>`${p.thicknessMm}mm ${p.grade} ${p.location}`.toLowerCase().includes(q)).map(p=>({title:`${p.thicknessMm} mm ${p.grade} plate`,meta:`${tonnes(p.availableKg)} · ${p.location}`,page:"stock" as PageKey})),
    ...customers.filter(c=>`${c.name} ${c.city} ${c.contact}`.toLowerCase().includes(q)).map(c=>({title:c.name,meta:`${c.city} · ${c.firm}`,page:"customers" as PageKey})),
    ...tenders.filter(t=>`${t.title} ${t.buyer} ${t.category}`.toLowerCase().includes(q)).map(t=>({title:t.title,meta:`${t.buyer} · closes ${formatDate(t.closingAt)}`,page:"tenders" as PageKey,id:t.id}))].slice(0,7)},[query]);
  if(!entered)return <Login show={showPassword} setShow={setShowPassword} enter={enter}/>;
  return <TooltipProvider><div className="app-shell">
    <Sidebar page={page} go={go} collapsed={collapsed} setCollapsed={setCollapsed} guide={()=>{setTourStep(0);setDetail({type:"guide"})}} reset={()=>setResetOpen(true)} mobile={mobileNav} close={()=>setMobileNav(false)}/>
    <div className="app-main"><header className="topbar"><button className="icon-button mobile-menu" onClick={()=>setMobileNav(true)} aria-label="Open navigation"><Menu size={20}/></button>
      <div className="search-wrap"><Search size={18}/><input aria-label="Search plates, customers and tenders" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search plates, customers, tenders…"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search"><X size={16}/></button>}{query.length>=2&&<div className="search-popover"><div className="search-caption">Search results</div>{results.length?results.map((r,i)=><button key={r.title+i} onClick={()=>{if(r.id)setDetail({type:"tenders",id:r.id});else go(r.page);setQuery("")}}><span>{r.title}</span><small>{r.meta}</small></button>):<div className="no-results">No sample records found.</div>}</div>}</div>
      <div className="topbar-meta"><CalendarDays size={16}/><span>8 Oct 2026</span></div><span className="demo-badge">Demo data</span>
      <DropdownMenu><DropdownMenuTrigger asChild><button className="profile-button"><span className="avatar">AK</span><span className="profile-copy"><b>Ajay Kumar</b><small>Owner</small></span><ChevronDown size={16}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel>Demo workspace</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={logout}>Return to login</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
    </header><main className="content-area">{page==="dashboard"?<Dashboard range={range} setRange={setRange} setDetail={setDetail} go={go}/>:<Scaffold page={page} go={go} setDetail={setDetail}/>}</main></div>
  </div><Details detail={detail} setDetail={setDetail} step={tourStep} setStep={setTourStep} go={go}/>
  <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset the demo?</AlertDialogTitle><AlertDialogDescription>This restores the original sample state and returns you to the dashboard. No business data is affected.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep exploring</AlertDialogCancel><AlertDialogAction onClick={reset}>Reset demo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></TooltipProvider>
}

function Login({show,setShow,enter}:{show:boolean;setShow:(v:boolean)=>void;enter:()=>void}){return <main className="login-page"><section className="login-form-side"><Brand/><div className="login-form-wrap"><div className="eyebrow">Business workspace</div><h1>Welcome to your<br/>business workspace.</h1><p>One place to follow steel stock, customer money and tender work.</p><form onSubmit={e=>{e.preventDefault();enter()}}><label htmlFor="username">Username</label><Input id="username" autoComplete="username" placeholder="demo@focaldiksha.in"/><label htmlFor="password">Password</label><div className="password-field"><Input id="password" type={show?"text":"password"} autoComplete="current-password" placeholder="Enter demo password"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><Button type="submit" className="login-primary">Sign in to demo</Button><button type="button" className="explore-button" onClick={enter}>Explore demo <ChevronRight size={17}/></button><small>Demo access only. Please do not enter real passwords.</small></form></div><div className="login-foot">Fixed demo clock · 8 October 2026, 10:00 AM IST</div></section><section className="login-visual-side"><div className="login-visual-panel"><div className="visual-heading"><span className="demo-badge">Interactive preview</span><h2>Your business, in one clear view.</h2><p>Track plates, prepare customer prices, follow payments and review tender opportunities.</p></div><div className="product-map"><div className="map-line horizontal"/><div className="map-line vertical"/><MapCard cls="map-stock" icon={<Archive/>} title="Stock" value="8 mm · 7.6 t" meta="18 pieces"/><MapCard cls="map-pricing" icon={<BadgeIndianRupee/>} title="Pricing" value="Jindal rates" meta="Customer markups"/><div className="map-centre"><div className="mini-logo">F</div><strong>Today</strong><span>4 priorities</span><div className="mini-bars"><i/><i/><i/><i/></div></div><MapCard cls="map-payments" icon={<CircleDollarSign/>} title="Payments" value="Collections" meta="Supplier dues"/><MapCard cls="map-tenders" icon={<BriefcaseBusiness/>} title="Tenders" value="2 to review" meta="1 deadline soon"/></div><div className="visual-caption"><span>From the godown to the owner’s desk.</span><span className="caption-line"/></div></div></section></main>}
function MapCard({cls,icon,title,value,meta}:{cls:string;icon:React.ReactNode;title:string;value:string;meta:string}){return <div className={`map-card ${cls}`}><div className="map-icon">{icon}</div><div><small>{title}</small><strong>{value}</strong><span>{meta}</span></div></div>}
function Brand({compact=false}:{compact?:boolean}){return <div className={`brand ${compact?"compact":""}`}><span className="brand-mark"><i/><i/><i/></span>{!compact&&<span><strong>Focal &amp; Diksha</strong><small>Business workspace</small></span>}</div>}

function Sidebar({page,go,collapsed,setCollapsed,guide,reset,mobile,close}:{page:PageKey;go:(p:PageKey)=>void;collapsed:boolean;setCollapsed:(v:boolean)=>void;guide:()=>void;reset:()=>void;mobile:boolean;close:()=>void}){return <><div className={`mobile-overlay ${mobile?"show":""}`} onClick={close}/><aside className={`sidebar ${collapsed?"collapsed":""} ${mobile?"mobile-open":""}`}><div className="sidebar-brand"><Brand compact={collapsed}/>{mobile&&<button onClick={close}><X/></button>}</div><nav>{navGroups.map(g=><div className="nav-group" key={g.label}><div className="nav-label">{!collapsed&&g.label}</div>{g.items.map(it=>{const Icon=it.icon;return <Tooltip key={it.key}><TooltipTrigger asChild><button className={page===it.key?"active":""} onClick={()=>go(it.key)}><Icon/><span>{it.label}</span></button></TooltipTrigger>{collapsed&&<TooltipContent side="right">{it.label}</TooltipContent>}</Tooltip>})}</div>)}</nav><div className="sidebar-bottom"><button onClick={guide}><Sparkles/><span>Demo guide</span></button><button onClick={reset}><RefreshCcw/><span>Reset demo</span></button><button className="desktop-collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}<span>Collapse sidebar</span></button></div></aside></>}

function Dashboard({range,setRange,setDetail,go}:{range:7|30;setRange:(r:7|30)=>void;setDetail:(d:Detail)=>void;go:(p:PageKey)=>void}){
 const data=useMemo(()=>{const dates=[...new Set(stockMovements.map(m=>m.date))].slice(range===7?-7:0);return dates.map(date=>({date,Receipts:+(stockMovements.filter(m=>m.date===date&&m.kind==="receipt").reduce((s,m)=>s+m.kg,0)/1000).toFixed(1),Dispatches:+(stockMovements.filter(m=>m.date===date&&m.kind==="dispatch").reduce((s,m)=>s+m.kg,0)/1000).toFixed(1)}))},[range]);
 const latest=[...tenders].sort((a,b)=>b.discoveredAt.localeCompare(a.discoveredAt)).slice(0,3), inv=invoices[0];
 const summary=[{label:"Available stock",value:tonnes(dashboardTotals.stockKg),sub:`${dashboardTotals.pieces} pieces`,icon:Archive,type:"stock" as const,tone:"sage"},{label:"Customer outstanding",value:compactMoney(dashboardTotals.customerOutstandingPaise),sub:`${compactMoney(dashboardTotals.overduePaise)} overdue`,icon:CircleDollarSign,type:"customers" as const,tone:"amber"},{label:"Supplier dues",value:compactMoney(dashboardTotals.supplierNext7Paise),sub:"Due in the next 7 days",icon:ReceiptIndianRupee,type:"suppliers" as const,tone:"plain"},{label:"Tenders to review",value:String(dashboardTotals.tendersToReview),sub:`${dashboardTotals.upcomingTenderCount} deadline in 7 days`,icon:BriefcaseBusiness,type:"tenders" as const,tone:"lime"}];
 const attention=[{id:"stock-low",icon:AlertTriangle,title:"8 mm plate below minimum",text:"7.6 t available · 9.0 t minimum",level:"warning"},{id:"invoice-overdue",icon:Clock3,title:"Narmada Fabricators overdue",text:`${compactMoney(outstandingFor(inv))} · due ${formatDate(inv.dueDate)}`,level:"danger"},{id:"dispatch-match",icon:FileCheck2,title:"Dispatch awaiting invoice match",text:"DSP-2134 · Narmada Fabricators",level:"neutral"},{id:"tender-close",icon:BriefcaseBusiness,title:"MPRDC tender closes soon",text:"Closes 11 Oct · review not started",level:"warning"}];
 return <><div className="page-heading"><div><div className="eyebrow">Thursday · 10:00 AM IST</div><h1>Business overview</h1><p>Stock, collections and today’s priorities.</p></div><button className="secondary-action" onClick={()=>setDetail({type:"guide"})}><Sparkles/> How this works</button></div>
 <section className="summary-grid">{summary.map(s=>{const Icon=s.icon;return <button key={s.label} className={`summary-card ${s.tone}`} onClick={()=>setDetail({type:s.type})}><div className="summary-top"><span>{s.label}</span><span className="summary-icon"><Icon/></span></div><strong>{s.value}</strong><small>{s.sub}</small><ChevronRight className="card-arrow"/></button>})}</section>
 <section className="dashboard-grid row-two"><div className="panel chart-panel"><PanelHeader title="Stock movement" subtitle="Receipts and dispatches, in tonnes"><div className="range-control"><button className={range===7?"active":""} onClick={()=>setRange(7)}>7 days</button><button className={range===30?"active":""} onClick={()=>setRange(30)}>30 days</button></div></PanelHeader><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:10,right:6,left:-18,bottom:0}}><defs><linearGradient id="rfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#718450" stopOpacity={.22}/><stop offset="100%" stopColor="#718450" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e5e5df"/><XAxis dataKey="date" tickFormatter={v=>formatDate(v,{day:"numeric",month:"short"})} axisLine={false} tickLine={false}/><YAxis unit="t" axisLine={false} tickLine={false}/><ChartTooltip formatter={v=>[`${v} tonnes`]} labelFormatter={v=>formatDate(v)} contentStyle={{border:"1px solid #deded7",borderRadius:10}}/><Legend iconType="circle" iconSize={8}/><Area type="monotone" dataKey="Receipts" stroke="#687b47" strokeWidth={2.2} fill="url(#rfill)"/><Area type="monotone" dataKey="Dispatches" stroke="#20241b" strokeWidth={2} fill="transparent" strokeDasharray="5 4"/></AreaChart></ResponsiveContainer></div></div>
 <div className="panel attention-panel"><PanelHeader title="Needs attention" subtitle="Four items to move today"/><div className="attention-list">{attention.map(a=>{const Icon=a.icon;return <button key={a.id} onClick={()=>setDetail({type:"attention",id:a.id})}><span className={`attention-icon ${a.level}`}><Icon/></span><span><strong>{a.title}</strong><small>{a.text}</small></span><ChevronRight/></button>})}</div></div></section>
 <section className="panel latest-tenders"><PanelHeader title="Latest tenders" subtitle="Recently added opportunities from sample portal records"><div className="header-actions"><span className="sample-label">Sample discoveries</span><button className="text-link" onClick={()=>go("tenders")}>View all tenders</button></div></PanelHeader><div className="tender-table-head"><span>Opportunity</span><span>Category</span><span>Closing</span><span>Discovered</span><span/></div>{latest.map(t=><div className="tender-row" key={t.id}><div><strong>{t.title}</strong><span>{t.buyer} · {t.portal}</span><small>{t.relevance}</small></div><div><span className="category-chip">{t.category}</span></div><div><strong>{formatDate(t.closingAt,{day:"numeric",month:"short"})}</strong><span>{formatDate(t.closingAt,{hour:"numeric",minute:"2-digit"})}</span></div><div><strong>{ago(t.discoveredAt)}</strong><span>{formatDate(t.discoveredAt,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})}</span></div><button className="row-action" onClick={()=>setDetail({type:"tenders",id:t.id})}>View details</button></div>)}</section>
 <section className="lower-grid"><div className="panel stock-bars"><PanelHeader title="Stock by thickness" subtitle="Available against minimum levels"/><div className="bar-legend"><span><i className="available"/>Available</span><span><i className="minimum"/>Minimum</span></div>{plates.map(p=>{const max=Math.max(p.availableKg,p.minimumKg)*1.18;return <button key={p.id} onClick={()=>setDetail({type:"stock",id:p.id})}><span className="bar-label">{p.thicknessMm} mm</span><span className="bar-track"><i style={{width:`${p.availableKg/max*100}%`}}/><em style={{left:`${p.minimumKg/max*100}%`}}/></span><strong className={p.availableKg<p.minimumKg?"low":""}>{tonnes(p.availableKg)}</strong></button>})}</div>
 <div className="panel"><PanelHeader title="Upcoming collections" subtitle="Customer bills requiring follow-up"/><SimpleList items={invoices.filter(i=>i.kind==="customer").slice(0,3).map(i=>({title:customers.find(c=>c.id===i.partyId)!.name,meta:`${i.id} · due ${formatDate(i.dueDate,{day:"numeric",month:"short"})}`,value:compactMoney(outstandingFor(i)),status:i.dueDate<"2026-10-08"?"Overdue":"Upcoming",action:()=>setDetail({type:"customers",id:i.id})}))}/></div>
 <div className="panel"><PanelHeader title="Tender deadlines" subtitle="What needs attention soon"/><SimpleList items={[...tenders].sort((a,b)=>a.closingAt.localeCompare(b.closingAt)).slice(0,3).map(t=>({title:t.buyer,meta:t.title,value:formatDate(t.closingAt,{day:"numeric",month:"short"}),status:t.status,action:()=>setDetail({type:"tenders",id:t.id})}))}/></div>
 <div className="panel rate-card"><div className="rate-icon"><BadgeIndianRupee/></div><div><span className="sample-label">Sample data</span><h3>Latest Jindal rate</h3><p>{priceLists[0].product} · {priceLists[0].grade}</p><strong>₹{(priceLists[0].pricePaisePerKg/100).toFixed(2)}<small>/kg</small></strong><div className="file-meta"><FileText/><span>{priceLists[0].sourceFilename}</span></div><small>Updated {formatDate(priceLists[0].updatedAt,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})}</small></div></div></section></>}

function PanelHeader({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>}
function SimpleList({items}:{items:{title:string;meta:string;value:string;status:string;action:()=>void}[]}){return <div className="simple-list">{items.map(x=><button key={x.title+x.value} onClick={x.action}><span><strong>{x.title}</strong><small>{x.meta}</small></span><span><strong>{x.value}</strong><small className={x.status==="Overdue"?"status-overdue":"status-review"}>{x.status}</small></span></button>)}</div>}

function Scaffold({page,go,setDetail}:{page:Exclude<PageKey,"dashboard">;go:(p:PageKey)=>void;setDetail:(d:Detail)=>void}){const s=scaffolds[page],Icon=s.icon;return <><div className="page-heading"><div><div className="eyebrow">Workspace module</div><h1>{s.title}</h1><p>{s.subtitle}</p></div><button className="secondary-action" onClick={()=>go("dashboard")}><ChevronLeft/> Back to overview</button></div><div className="scaffold-panel"><div className="scaffold-icon"><Icon/></div><span className="sample-label">{page==="tenders"?"Existing demo workflow":"Stage two preview"}</span><h2>{s.copy}</h2><p>{page==="tenders"?"The sample pipeline remains separate from live discovery below.":"This demo section is being prepared."}</p><div className="scope-list">{s.bullets.map((b,i)=><div key={b}><span>{String(i+1).padStart(2,"0")}</span><strong>{b}</strong><CheckCircle2/></div>)}</div>{page==="tenders"&&<div className="scaffold-tenders"><h3>Sample tender pipeline</h3>{tenders.map(t=><button key={t.id} onClick={()=>setDetail({type:"tenders",id:t.id})}><span><strong>{t.title}</strong><small>{t.buyer}</small></span><span className="category-chip">{t.status}</span><ChevronRight/></button>)}</div>}</div>{page==="tenders"&&<TenderDiscovery/>}</>}

function Details({detail,setDetail,step,setStep,go}:{detail:Detail;setDetail:(d:Detail)=>void;step:number;setStep:(n:number)=>void;go:(p:PageKey)=>void}){const tender=detail?.type==="tenders"&&detail.id?tenders.find(t=>t.id===detail.id):undefined;const titles:{[k:string]:string}={stock:"Available stock",customers:"Customer outstanding",suppliers:"Supplier dues",tenders:"Tenders to review",attention:"Priority details",guide:"How this works"};return <Sheet open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><SheetContent className="detail-sheet sm:max-w-[520px]"><SheetHeader><div className="drawer-kicker">Focal &amp; Diksha · Demo data</div><SheetTitle>{tender?.title??titles[detail?.type??""]}</SheetTitle><SheetDescription>{tender?"A fictional opportunity record for this sales demonstration.":detail?.type==="guide"?"A five-step tour of the proposed workspace.":"Calculated from the connected sample records."}</SheetDescription></SheetHeader><div className="drawer-body">
 {detail?.type==="stock"&&<><Metric items={[{label:"Available",value:tonnes(dashboardTotals.stockKg)},{label:"Pieces",value:String(dashboardTotals.pieces)},{label:"Below minimum",value:"1 thickness"}]}/>{plates.map(p=><Record key={p.id} a={`${p.thicknessMm} mm · ${p.grade}`} b={`${p.firm} · ${p.location}`} c={tonnes(p.availableKg)} d={`${p.pieces} pieces`} danger={p.availableKg<p.minimumKg}/>)}</>}
 {detail?.type==="customers"&&<><Metric items={[{label:"Outstanding",value:compactMoney(dashboardTotals.customerOutstandingPaise)},{label:"Overdue",value:compactMoney(dashboardTotals.overduePaise)}]}/>{invoices.filter(i=>i.kind==="customer").map(i=><Record key={i.id} a={customers.find(c=>c.id===i.partyId)!.name} b={`${i.id} · due ${formatDate(i.dueDate)}`} c={compactMoney(outstandingFor(i))} d={i.firm}/>)}</>}
 {detail?.type==="suppliers"&&<><Metric items={[{label:"Next 7 days",value:compactMoney(dashboardTotals.supplierNext7Paise)},{label:"Open bills",value:"3"}]}/>{invoices.filter(i=>i.kind==="supplier").map(i=><Record key={i.id} a={suppliers.find(s=>s.id===i.partyId)!.name} b={`${i.id} · due ${formatDate(i.dueDate)}`} c={compactMoney(outstandingFor(i))} d={i.tallyRef}/>)}</>}
 {detail?.type==="tenders"&&!tender&&tenders.filter(t=>t.status==="New"||t.status==="Reviewing").map(t=><button className="drawer-action-record" key={t.id} onClick={()=>setDetail({type:"tenders",id:t.id})}><div><strong>{t.title}</strong><span>{t.buyer} · closes {formatDate(t.closingAt)}</span></div><ChevronRight/></button>)}
 {tender&&<TenderDetail tender={tender}/>} {detail?.type==="attention"&&<Attention id={detail.id}/>} {detail?.type==="guide"&&<Guide step={step} setStep={setStep}/>}</div>
 {detail?.type==="guide"&&<div className="drawer-footer"><Button variant="outline" onClick={()=>setDetail(null)}>Close guide</Button>{step<4?<Button onClick={()=>setStep(step+1)}>Next step <ChevronRight/></Button>:<Button onClick={()=>{setDetail(null);go("dashboard")}}>Finish tour</Button>}</div>}</SheetContent></Sheet>}
function Metric({items}:{items:{label:string;value:string}[]}){return <div className="metric-strip">{items.map(x=><div key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div>}
function Record({a,b,c,d,danger}:{a:string;b:string;c:string;d:string;danger?:boolean}){return <div className="drawer-record"><div><strong>{a}</strong><span>{b}</span></div><div><strong className={danger?"danger-text":""}>{c}</strong><span>{d}</span></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><strong>{value}</strong></div>}
function TenderDetail({tender}:{tender:Tender}){return <div className="tender-detail"><div className="demo-note"><Sparkles/><span>This is a demonstration record. No live portal search or notice link is connected.</span></div><div className="detail-grid"><Info label="Reference" value={tender.reference}/><Info label="Review status" value={tender.status}/><Info label="Buyer" value={tender.buyer}/><Info label="Sample source" value={tender.portal}/><Info label="Discovered" value={formatDate(tender.discoveredAt,{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"})}/><Info label="Closes" value={formatDate(tender.closingAt,{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"})}/><Info label="Quantity" value={tender.quantity}/><Info label="EMD" value={tender.emdPaise?money(tender.emdPaise):"Not specified"}/></div><div className="detail-section"><h3>Product requirements</h3><p>{tender.requirements}</p></div><div className="detail-section"><h3>Sample document checklist</h3>{tender.checklist.map((c,i)=><div className="check-item" key={c}><span className={i<2?"done":""}>{i<2?<CheckCircle2/>:<span/>}</span>{c}<small>{i<2?"Ready":"To prepare"}</small></div>)}</div></div>}
function Attention({id}:{id?:string}){const data:{[k:string]:{icon:React.ReactNode;title:string;copy:string;facts:string[][]}}={"stock-low":{icon:<Archive/>,title:"8 mm E250 BR is below minimum",copy:"Available stock is 1.4 tonnes below the sample reorder level.",facts:[["Available","7.6 tonnes"],["Minimum","9.0 tonnes"],["Location","Bay A2"],["Next action","Confirm Jindal availability"]]},"invoice-overdue":{icon:<Clock3/>,title:"Customer bill is overdue",copy:"Narmada Fabricators has a partially paid bill past its due date.",facts:[["Invoice","INV-1041"],["Outstanding",compactMoney(outstandingFor(invoices[0]))],["Due date","3 Oct 2026"],["Next action","Call accounts contact"]]},"dispatch-match":{icon:<FileCheck2/>,title:"Dispatch awaiting invoice match",copy:"The goods moved, but the sample Tally invoice representation has not been linked.",facts:[["Dispatch","DSP-2134"],["Weight",tonnes(dispatches[0].kg)],["Vehicle",dispatches[0].vehicle],["Next action","Match Tally invoice"]]},"tender-close":{icon:<BriefcaseBusiness/>,title:"MPRDC tender closes soon",copy:"The opportunity is relevant and still marked New.",facts:[["Reference",tenders[0].reference],["Closing","11 Oct, 3:00 PM"],["Quantity",tenders[0].quantity],["Next action","Start review checklist"]]}};const d=data[id??""]??data["stock-low"];return <div className="attention-detail"><div className="attention-hero"><span>{d.icon}</span><div><h3>{d.title}</h3><p>{d.copy}</p></div></div>{d.facts.map(f=><Info key={f[0]} label={f[0]} value={f[1]}/>)}</div>}
function Guide({step,setStep}:{step:number;setStep:(n:number)=>void}){const steps=[{icon:PackageCheck,title:"Record the material",copy:"Staff record plate receipts and dispatches, including heat numbers, test certificates and locations."},{icon:BadgeIndianRupee,title:"Prepare customer prices",copy:"Sample Jindal files provide base prices, then approved customer-specific markups build the price list."},{icon:BookOpen,title:"See accounting context",copy:"A future read-only Tally connection supplies ledger and invoice information. Official GST invoices remain in Tally."},{icon:BriefcaseBusiness,title:"Review tender opportunities",copy:"Relevant sample opportunities, deadlines and document checklists appear in one tender workspace."},{icon:LayoutDashboard,title:"Act on the priorities",copy:"The owner sees resulting summaries, exceptions and next actions on this dashboard."}];const s=steps[step],Icon=s.icon;return <div className="guide"><div className="guide-progress">{steps.map((_,i)=><button aria-label={`Go to step ${i+1}`} className={i<=step?"active":""} onClick={()=>setStep(i)} key={i}/>)}</div><div className="guide-number">Step {step+1} of {steps.length}</div><div className="guide-icon"><Icon/></div><h3>{s.title}</h3><p>{s.copy}</p><div className="demo-note"><Sparkles/><span>All information shown is sample data. Portal search, Tally and file integrations are simulated in this first-stage demo.</span></div></div>}
