"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, Bookmark, BookmarkCheck, CheckCircle2, ChevronDown, ExternalLink, LoaderCircle, Search, ShieldCheck, Square, SquareCheck, StopCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import type { NormalizedTender, SourceId, SourceResult } from "@/lib/tenders/types";

type LiveTender=NormalizedTender&{saved?:boolean};
type SourceInfo={label:string;enabled:boolean;url:string;host:string;availability:"available"|"partial"|"unavailable";reason:string;checkedAt:string;robotsUrl:string;robotsOutcome:string;policyUrl:string;accessOutcome:string};
type SourceStatus={source:string;status:string;checked_at:string;last_success_at:string|null;last_error:string|null;coverage:string;pages_checked:number;listings_inspected:number;matches_found:number};
type Checking={status:"checking";pagesChecked:number;listingsInspected:number;matchCount:number};
type ApiData={sources:Record<SourceId,SourceInfo>;statuses:SourceStatus[];lastRun:Record<string,unknown>|null;tenders:LiveTender[];serverTime:string};

const enabledIds:SourceId[]=["cppp","gem","coal-india","up-etender","ntpc"];
const groupMap:Record<string,string[]>={Metals:["Steel plates","Steel coils","Hollow sections & tubes","Steel rails","Angles & channels","Beams & columns","Wire rods","Steel round bars"],Tools:["Measuring tools","HSS cutting tools","Indexable tooling","Tapping & collets"],Consumables:["Industrial oils & lubricants","Welding consumables","Welding PPE","Adhesives & sealants"]};
const fmt=(v:string|null,unknown="Not available")=>v?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(v)):unknown;
const relevanceRank={strong:0,possible:1,"works-service":2};

export function TenderDiscovery(){
  const [data,setData]=useState<ApiData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[running,setRunning]=useState(false),[cancelled,setCancelled]=useState(false);
  const [sources,setSources]=useState<SourceId[]>(enabledIds),[groups,setGroups]=useState<string[]>(Object.keys(groupMap)),[lookback,setLookback]=useState(30),[sort,setSort]=useState("newest"),[selected,setSelected]=useState<LiveTender|null>(null);
  const [progress,setProgress]=useState<Record<string,SourceResult|Checking>>({}),[runId,setRunId]=useState<string|null>(null);
  const abortRef=useRef<AbortController|null>(null);
  const load=async()=>{try{const r=await fetch("/api/tenders",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load tender discovery");setData(j);setError(null)}catch(e){setError(e instanceof Error?e.message:"Could not load tender discovery")}finally{setLoading(false)}};
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[]);
  const toggleSource=(id:SourceId)=>setSources(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  const toggleGroup=(g:string)=>setGroups(s=>s.includes(g)?s.filter(x=>x!==g):[...s,g]);

  async function start(){
    if(running||!sources.length)return;setRunning(true);setCancelled(false);setProgress({});setError(null);abortRef.current=new AbortController();
    let id:string|null=null;
    try{
      const startRes=await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",sources}),signal:abortRef.current.signal});const startJson=await startRes.json();if(!startRes.ok)throw new Error(startJson.error||"Could not start search");id=startJson.runId;setRunId(id);
      for(const source of sources){
        if(abortRef.current.signal.aborted)break;setProgress(p=>({...p,[source]:{status:"checking",pagesChecked:0,listingsInspected:0,matchCount:0}}));
        // Large sources answer in batches; keep requesting until the server returns no cursor, summing counts and matches.
        let cursor:string|null=null,total:SourceResult|null=null;
        do{
          const response=await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"fetch-source",runId:id,source,lookback,cursor}),signal:abortRef.current.signal});const result=await response.json() as SourceResult&{error?:string};
          if(!response.ok)throw new Error(result.error||`Could not check ${source}`);
          const merged:SourceResult=total?{...result,pagesChecked:total.pagesChecked+result.pagesChecked,listingsInspected:total.listingsInspected+result.listingsInspected,matches:[...new Map([...total.matches,...result.matches].map(m=>[m.key,m])).values()]}:result;
          total=merged;cursor=result.canContinue&&result.cursor?result.cursor:null;
          setProgress(p=>({...p,[source]:cursor?{status:"checking",pagesChecked:merged.pagesChecked,listingsInspected:merged.listingsInspected,matchCount:merged.matches.length}:merged}));
        }while(cursor&&!abortRef.current.signal.aborted);
      }
      if(!abortRef.current.signal.aborted)await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",runId:id})});
    }catch(e){if((e as Error).name!=="AbortError")setError(e instanceof Error?e.message:"Search failed")}finally{setRunning(false);setRunId(null);abortRef.current=null;await load()}
  }
  async function cancel(){setCancelled(true);abortRef.current?.abort();if(runId)await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"cancel",runId})});setRunning(false)}
  async function save(t:LiveTender){const action=t.saved?"unsave":"save";const r=await fetch("/api/tenders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,key:t.key})});if(r.ok){setData(d=>d?{...d,tenders:d.tenders.map(x=>x.key===t.key?{...x,saved:!t.saved}:x)}:d);setSelected(s=>s?.key===t.key?{...s,saved:!t.saved}:s)}}

  const visible=useMemo(()=>{
    const allowed=new Set(groups.flatMap(g=>groupMap[g]));
    const items=groups.length?(data?.tenders??[]).filter(t=>t.matchedCategories.some(c=>allowed.has(c))||t.matchedCategories.includes("Brand-supported possible match")):[];
    return [...items].sort((a,b)=>sort==="closing"?(a.closingAt?new Date(a.closingAt).getTime():Infinity)-(b.closingAt?new Date(b.closingAt).getTime():Infinity):sort==="relevance"?relevanceRank[a.relevance]-relevanceRank[b.relevance]:(b.publishedAt?new Date(b.publishedAt).getTime():0)-(a.publishedAt?new Date(a.publishedAt).getTime():0));
  },[data,groups,sort]);
  const progressItems=Object.entries(progress),totals=progressItems.reduce((a,[,r])=>r.status==="checking"?a:{pages:a.pages+r.pagesChecked,listings:a.listings+r.listingsInspected,matches:a.matches+r.matches.length,partial:a.partial+(r.status==="partial"?1:0),errors:a.errors+(["unavailable","restricted","parser-failure"].includes(r.status)?1:0)}, {pages:0,listings:0,matches:0,partial:0,errors:0});
  const lastSuccess=data?.statuses.filter(s=>s.last_success_at).sort((a,b)=>String(b.last_success_at).localeCompare(String(a.last_success_at)))[0]?.last_success_at??null;

  return <section className="discovery-section">
    <div className="discovery-head"><div><span className="live-label"><span/> Live public listings</span><h2>Find new tenders</h2><p>Checks available public listings for products your business supplies.</p></div><div className="last-fetch"><span>Last successful fetch</span><strong>{fmt(lastSuccess,"Not fetched yet")}</strong></div></div>
    <div className="discovery-layout"><aside className="discovery-controls"><div className="control-block"><label>Sources</label><div className="source-options">{data?Object.entries(data.sources).map(([id,s])=><button key={id} disabled={!s.enabled||running} onClick={()=>toggleSource(id as SourceId)} className={!s.enabled?"unavailable":""}><span className="check-box">{sources.includes(id as SourceId)&&s.enabled?<SquareCheck/>:<Square/>}</span><span><strong>{s.label}</strong><small>{s.enabled?(s.availability==="partial"?"Available · capped":"Available"):"Unavailable"}</small></span><span className={`source-dot ${s.enabled?"partial":"off"}`}/><span className="source-reason">{s.reason}</span></button>):<div className="control-skeleton">Checking source availability…</div>}</div></div>
      <div className="control-block"><label>Product groups</label><div className="filter-chips">{Object.keys(groupMap).map(g=><button key={g} disabled={running} className={groups.includes(g)?"active":""} onClick={()=>toggleGroup(g)}>{g}</button>)}</div></div>
      <div className="control-block"><label htmlFor="lookback">Publication lookback</label><div className="select-wrap"><select id="lookback" value={lookback} disabled={running} onChange={e=>setLookback(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={60}>Last 60 days</option><option value={90}>Last 90 days</option></select><ChevronDown/></div><small>Sources without publication dates are included and clearly labelled.</small></div>
      {!running?<Button className="discover-button" onClick={start} disabled={loading||!sources.length}><Search/> Find new tenders</Button>:<Button variant="outline" className="discover-button stop" onClick={cancel}><StopCircle/> Cancel search</Button>}
      <div className="internal-note"><ShieldCheck/><span>Internal review only. Results are factual source metadata, not an eligibility decision.</span></div>
      {data&&<details className="source-audit"><summary>Source verification record</summary>{Object.entries(data.sources).map(([id,s])=><div key={id}><strong>{s.label}</strong><span>Checked {s.checkedAt} · {s.accessOutcome}</span><a href={s.url} target="_blank" rel="noopener noreferrer">Listing</a><a href={s.robotsUrl} target="_blank" rel="noopener noreferrer">Robots</a><a href={s.policyUrl} target="_blank" rel="noopener noreferrer">Policy</a><small>{s.robotsOutcome}</small></div>)}</details>}
    </aside>
    <div className="discovery-main">
      {(running||progressItems.length>0)&&<div className="run-progress"><div className="run-progress-head"><div><strong>{running?"Search in progress":cancelled?"Search cancelled":"Search finished"}</strong><span>{totals.pages} pages checked · {totals.listings} listings inspected · {totals.matches} relevant matches</span></div>{running&&<LoaderCircle className="spin"/>}</div><div className="source-progress-list">{sources.map(id=>{const p=progress[id],label=data?.sources[id].label??id;if(!p)return <div key={id}><span className="progress-icon waiting"/><span><strong>{label}</strong><small>Waiting</small></span></div>;if(p.status==="checking")return <div key={id}><LoaderCircle className="spin"/><span><strong>{label}</strong><small>{p.pagesChecked?`Checking… ${p.pagesChecked} requests · ${p.listingsInspected} listings · ${p.matchCount} matches so far`:"Checking public listing…"}</small></span></div>;return <div key={id}><span className={`progress-icon ${p.status}`}>{["completed","partial"].includes(p.status)?<CheckCircle2/>:<AlertCircle/>}</span><span><strong>{label}</strong><small>{p.pagesChecked} page{p.pagesChecked===1?"":"s"} · {p.listingsInspected} listings · {p.matches.length} matches{p.fromCache?" · saved result":""}</small>{p.error&&<em>{p.error}</em>}</span></div>})}</div></div>}
      {error&&<div className="discovery-error"><AlertCircle/><div><strong>Discovery could not complete</strong><span>{error}</span></div></div>}
      <div className="results-toolbar"><div><h3>Discovery results</h3><span>{loading?"Loading saved results…":`${visible.length} active result${visible.length===1?"":"s"} · ${data?.tenders.filter(t=>t.saved).length??0} saved for review`}</span></div><div className="select-wrap sort"><select aria-label="Sort discovery results" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest publication</option><option value="closing">Nearest closing</option><option value="relevance">Relevance</option></select><ChevronDown/></div></div>
      {!loading&&visible.length===0?<div className="discovery-empty"><Search/><h3>No relevant active tenders in saved results</h3><p>Run a search to check the selected public listings. A completed zero-result search is different from an unavailable or partial source.</p></div>:<div className="live-results">{visible.map(t=><article key={t.key}><div className="result-top"><span className={`relevance-tag ${t.relevance}`}>{t.relevance==="strong"?"Strong product match":t.relevance==="possible"?"Possible match · review":"Works/service · lower relevance"}</span>{t.saved&&<span className="saved-tag"><BookmarkCheck/> Saved</span>}</div><h3>{t.title}</h3><p>{t.buyer??"Buyer not available"}</p><div className="result-meta"><span><small>Category</small><strong>{t.matchedCategories.join(", ")}</strong></span><span><small>Source</small><strong>{t.sourceLabel}</strong></span><span><small>Published</small><strong>{fmt(t.publishedAt)}</strong></span><span><small>Closing</small><strong>{fmt(t.closingAt,"Closing date unverified")}</strong></span></div><div className="match-reason">Matched source words: <b>{t.evidence.join(", ")||"brand reference"}</b></div><div className="result-actions"><button onClick={()=>setSelected(t)}>View details</button><a href={t.detailUrl} target="_blank" rel="noopener noreferrer">Open original notice <ExternalLink/></a></div></article>)}</div>}
      {data?.lastRun&&<div className="run-summary">Latest run: {String(data.lastRun.status)} · {Number(data.lastRun.completed_sources||0)+Number(data.lastRun.partial_sources||0)+Number(data.lastRun.error_sources||0)} sources checked · {String(data.lastRun.listings_inspected??0)} listings inspected · {String(data.lastRun.matches_found??0)} matches. Results above may include previously saved records.</div>}
    </div></div>
    <Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent className="detail-sheet live-detail sm:max-w-[560px]"><SheetHeader><div className="drawer-kicker">Live discovery · {selected?.sourceLabel}</div><SheetTitle>{selected?.title}</SheetTitle><SheetDescription>Verified source metadata with explainable matching evidence.</SheetDescription></SheetHeader>{selected&&<div className="drawer-body"><div className="live-trace-note"><ShieldCheck/><span>Fetched from a reviewed public listing. Missing fields remain unverified; this is not an eligibility assessment.</span></div><div className="detail-grid"><Info label="Reference" value={selected.reference}/><Info label="Buyer" value={selected.buyer??"Not available"}/><Info label="Published" value={fmt(selected.publishedAt)}/><Info label="Closing" value={fmt(selected.closingAt,"Closing date unverified")}/><Info label="Relevance" value={selected.relevance==="strong"?"Strong product match":selected.relevance==="possible"?"Possible match · needs review":"Works/service · lower relevance"}/><Info label="Matched category" value={selected.matchedCategories.join(", ")}/><Info label="First discovered" value={fmt(selected.firstDiscoveredAt)}/><Info label="Last verified" value={fmt(selected.lastVerifiedAt)}/></div><div className="detail-section"><h3>Match evidence</h3><p>Words found in the source listing: <strong>{selected.evidence.join(", ")||"Brand term"}</strong>.</p></div><div className="detail-section"><h3>Source trace</h3><p>Source tender ID: {selected.sourceTenderId}<br/>Fetch run: {selected.fetchRunId}</p></div><div className="live-detail-actions"><Button onClick={()=>save(selected)} variant={selected.saved?"outline":"default"}>{selected.saved?<BookmarkCheck/>:<Bookmark/>}{selected.saved?"Saved for review":"Save for review"}</Button><a href={selected.detailUrl} target="_blank" rel="noopener noreferrer">Open original notice <ExternalLink/></a></div></div>}</SheetContent></Sheet>
  </section>
}
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><strong>{value}</strong></div>}
