import type { SourceId } from "./types.ts";

export const SOURCES:Record<SourceId,{label:string;enabled:boolean;url:string;host:string;availability:"available"|"partial"|"unavailable";reason:string;checkedAt:string;robotsUrl:string;robotsOutcome:string;policyUrl:string;accessOutcome:string}>={
  cppp:{label:"CPPP",enabled:true,url:"https://eprocure.gov.in/cppp/latestactivetendersnew/cpppdata",host:"eprocure.gov.in",availability:"partial",reason:"Public listing verified. Search is CAPTCHA-protected; discovery is capped at 3 newest pages (30 listings).",checkedAt:"2026-10-08",robotsUrl:"https://eprocure.gov.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://eprocure.gov.in/cppp/disclaimer/#Terms_of_Use",accessOutcome:"Public rows and pagination verified; internal factual metadata only."},
  "coal-india":{label:"Coal India eProcurement",enabled:true,url:"https://coalindiatenders.nic.in/nicgep/app",host:"coalindiatenders.nic.in",availability:"partial",reason:"Public homepage feed verified. Limited to up to 10 latest tenders and does not provide publication dates.",checkedAt:"2026-10-08",robotsUrl:"https://coalindiatenders.nic.in/robots.txt",robotsOutcome:"The standard robots URL redirects to the homepage; no rules file was returned.",policyUrl:"https://coalindiatenders.nic.in/nicgep/app?page=Disclaimer&service=page",accessOutcome:"Public homepage rows verified. CAPTCHA-protected search is not used."},
  "up-etender":{label:"UP eTender",enabled:true,url:"https://etender.up.nic.in/nicgep/app",host:"etender.up.nic.in",availability:"partial",reason:"Public homepage feed verified. Limited to up to 10 latest tenders and does not provide publication dates.",checkedAt:"2026-10-08",robotsUrl:"https://etender.up.nic.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://etender.up.nic.in/nicgep/app?page=Disclaimer&service=page",accessOutcome:"Public homepage rows verified. CAPTCHA-protected search is not used."},
  ntpc:{label:"NTPC Tender",enabled:false,url:"https://ntpctender.ntpc.co.in",host:"ntpctender.ntpc.co.in",availability:"unavailable",reason:"Listing rows and a working terms route could not be verified from the server runtime; no automated fetch is attempted.",checkedAt:"2026-10-08",robotsUrl:"https://ntpctender.ntpc.co.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://ntpctender.ntpc.co.in/Index/TermsandConditions",accessOutcome:"Homepage loaded, but server-readable rows were absent and the linked terms route returned 404. Disabled."}
};
export const ENABLED_SOURCES=(Object.keys(SOURCES) as SourceId[]).filter(id=>SOURCES[id].enabled);
