import type { SourceId } from "./types.ts";

export const SOURCES:Record<SourceId,{label:string;enabled:boolean;url:string;host:string;availability:"available"|"partial"|"unavailable";reason:string;checkedAt:string;robotsUrl:string;robotsOutcome:string;policyUrl:string;accessOutcome:string}>={
  cppp:{label:"CPPP",enabled:true,url:"https://eprocure.gov.in/cppp/latestactivetendersnew/cpppdata",host:"eprocure.gov.in",availability:"partial",reason:"Public listing verified. Searches up to 15 newest pages in batches of 3; Continue search resumes from the portal's next-page link. Keyword search remains CAPTCHA-protected.",checkedAt:"2026-10-08",robotsUrl:"https://eprocure.gov.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://eprocure.gov.in/cppp/disclaimer/#Terms_of_Use",accessOutcome:"Public rows and pagination verified; internal factual metadata only."},
  "coal-india":{label:"Coal India eProcurement",enabled:true,url:"https://coalindiatenders.nic.in/nicgep/app",host:"coalindiatenders.nic.in",availability:"partial",reason:"Public homepage feed only, up to 10 latest tenders. The broader Active Tenders route requires CAPTCHA and is not automated; publication dates are unavailable.",checkedAt:"2026-10-08",robotsUrl:"https://coalindiatenders.nic.in/robots.txt",robotsOutcome:"The standard robots URL redirects to the homepage; no rules file was returned.",policyUrl:"https://coalindiatenders.nic.in/nicgep/app?page=Disclaimer&service=page",accessOutcome:"Public homepage rows verified. CAPTCHA-protected search is not used."},
  "up-etender":{label:"UP eTender",enabled:true,url:"https://etender.up.nic.in/nicgep/app",host:"etender.up.nic.in",availability:"partial",reason:"Public homepage feed only, up to 10 latest tenders. The broader Active Tenders route requires CAPTCHA and is not automated; publication dates are unavailable.",checkedAt:"2026-10-08",robotsUrl:"https://etender.up.nic.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://etender.up.nic.in/nicgep/app?page=Disclaimer&service=page",accessOutcome:"Public homepage rows verified. CAPTCHA-protected search is not used."},
  gem:{label:"GeM Bids",enabled:true,url:"https://bidplus.gem.gov.in/all-bids",host:"bidplus.gem.gov.in",availability:"partial",reason:"Public GeM bid search, run as keyword searches for each product group (newest first, up to 3 result pages per keyword within the lookback). GeM search is fuzzy, so every bid is still checked by the product matcher.",checkedAt:"2026-10-08",robotsUrl:"https://bidplus.gem.gov.in/robots.txt",robotsOutcome:"robots.txt allows /all-bids and /all-bids-data; only /resources/ and bank-guarantee service paths are disallowed.",policyUrl:"https://gem.gov.in/termsAndConditions",accessOutcome:"Public ongoing-bid search verified without login or CAPTCHA; uses the page's own session cookie and form token."},
  ntpc:{label:"NTPC Tender",enabled:true,url:"https://ntpctender.ntpc.co.in/Index/Search",host:"ntpctender.ntpc.co.in",availability:"available",reason:"Public server-rendered Live Tenders table verified. The whole table is read in one bounded response; publication dates and closing times are not supplied.",checkedAt:"2026-10-08",robotsUrl:"https://ntpctender.ntpc.co.in/robots.txt",robotsOutcome:"404 — no robots.txt rules were published at the standard location.",policyUrl:"https://ntpctender.ntpc.co.in/Index/Disclaimer",accessOutcome:"Public Live Tenders table, detail links and official disclaimer verified. No login or CAPTCHA is used."}
};
export const ENABLED_SOURCES=(Object.keys(SOURCES) as SourceId[]).filter(id=>SOURCES[id].enabled);
